version: '3.8'

services:
  # 轉錄主程式 (Node.js)
  echoscript:
    build: .
    container_name: echoscript-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    networks:
      - echo-net

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: echoscript-nginx
    restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/certs:ro # 掛載您剛才準備好的 ssl 目錄
    depends_on:
      - echoscript
    networks:
      - echo-net

networks:
  echo-net:
    driver: bridge
